# Generated by Django 3.1.14 on 2022-06-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcardstack', '0003_remove_flashcard_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='notice_lvl_in_days',
            field=models.IntegerField(),
        ),
    ]
