# Generated by Django 3.1.14 on 2022-05-28 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcardstack', '0002_auto_20220528_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='user',
        ),
    ]
